-- Add a test user for local development
-- This will allow you to sign in and test the app

-- First, create the auth user
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at,
    is_sso_user,
    deleted_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '12345678-1234-5678-9012-123456789012',
    'authenticated',
    'authenticated',
    'test@test.com',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NOW(),
    '',
    NULL,
    '',
    '',
    NULL,
    NULL,
    '{"provider":"email","providers":["email"]}',
    '{}',
    FALSE,
    NOW(),
    NOW(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    FALSE,
    NULL
) ON CONFLICT (id) DO NOTHING;

-- Create the corresponding public user profile
INSERT INTO public.users (
    id,
    auth_id,
    email,
    first_name,
    last_name,
    display_name,
    role,
    is_active,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    '12345678-1234-5678-9012-123456789012',
    'test@test.com',
    'Test',
    'User',
    'Test User',
    'admin',
    true,
    NOW(),
    NOW()
) ON CONFLICT (auth_id) DO NOTHING;